# Generated by Django 5.1.4 on 2024-12-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_id', models.TextField()),
                ('name', models.TextField()),
                ('brand', models.TextField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('offer_price', models.IntegerField()),
                ('color', models.TextField()),
                ('stock', models.IntegerField()),
                ('warranty', models.TextField()),
                ('img', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='phone',
            name='specifications',
            field=models.TextField(default='Not specified'),
        ),
    ]
